// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockAssertTestingT is an autogenerated mock type for the MockAssertTestingT type
type MockAssertTestingT struct {
	mock.Mock
}

// Errorf provides a mock function with given fields: format, args
func (_m *MockAssertTestingT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// NewMockAssertTestingT creates a new instance of MockAssertTestingT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAssertTestingT(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAssertTestingT {
	mock := &MockAssertTestingT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
