// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockRequireTestingT is an autogenerated mock type for the MockRequireTestingT type
type MockRequireTestingT struct {
	mock.Mock
}

// Errorf provides a mock function with given fields: format, args
func (_m *MockRequireTestingT) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// FailNow provides a mock function with no fields
func (_m *MockRequireTestingT) FailNow() {
	_m.Called()
}

// NewMockRequireTestingT creates a new instance of MockRequireTestingT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequireTestingT(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequireTestingT {
	mock := &MockRequireTestingT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
